# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: /go/src/bitbucket.org/ryaneoinwave/circletest
    steps:
      - checkout
      - run: echo "A First Hello!"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output

  two:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: /go/src/bitbucket.org/ryaneoinwave/circletest
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - attach_workspace:
        at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
        requires:
          - one
